[[!Login?
	&tplType=`modChunk`
	&loginTpl=`ctred.login_form`
	&logoutTpl=`ctred.logout_form`
	&loginResourceId=`[[++commerce.login_resource]]`
	&logoutResourceId=`[[++ctred.you_are_logout_page_id]]`
	&preHooks=`csrfhelper_login`
    &csrfKey=`login`
]]